### ISSUE TITLE
Migration Start Flow actions

### ISSUE THREAD

**Issue by ericnewcomer** [nyaruka/goflow#139]
Contacts within a flow should only ever go through subflows. This task is two parts:

* Action for terminating existing flow runs
* Migrate current start flow actions to be subflows preceded by the above new action

**Comment by rowanseymour** [comment]
We chatted about this and agreed:

1. For now we add a flag to `StartFlowAction` so it can exit existing runs instead of resuming them. This will match old engine behaviour.
2. In future we might migrate all those to be their own node, and the editor provides and advanced option regarding whether to return into the current flow or not.
