### ISSUE TITLE
String equality/inequality

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#245]
In #212 we made `=`, `!=`, `>=`, `>`, `<=`, `<` require numbers as arguments rather than the legacy behavior of doing either numerical or lexical comparison based on the argument types. We added `string_cmp` which is fine for the unlikely case that someone needs to do lexical comparison of values, but `string_cmp(foo, bar) == 0` is hardly ideal for the common case of `foo = bar` where both args are strings.

We also have no easy migration path from an expression like `@(contact.language = "eng")`

**Comment by nicpottier** [comment]
For the migration case we could figure out if one side is a string, but gets weirder still when they are flow values, ie:

`@(contact.language = flow.results.language)`

Which kind of brings up the point that flow values are all strings but might not "feel" that way to users (same with contact fields) which really makes me think we either need to be super permissive or super strict, but can't be in the middle.

Seems like whatever we do with `=` we would have to do with `>`,`<` etc..

The weird case is of course equality cases between `"2.0"` and the decimal `2`, which is super ambiguous, I could think of cases where the user would expect true or false there.

`>` and `<` are weird from a string equality point of view, so maybe that points to keeping that for decimals only and then having a `string_eq` to simplify the equality case? And then a `legacy_cmp` to go with our `legacy_add`? (do we need this anyways because we supported `>` and `<` for strings in the old world?)

That's definitely ugly.

One question.. is decimal equality every actually different than string equality? That is, for the case above, if the stringified value for a decimal is always optimized to not have trailing zeros, then that actually becomes `"2"` and `2` which sure feels equal to me. So maybe that's an argument towards `=` always being string equality. (and then maybe just smushing our faces and saying `<` and `>` are different and need the be numbers otherwise you get into weird shit like `100` < `2`)

**Comment by rowanseymour** [comment]
We've chatted and yeah it seems like `=` and `!=` can always be string comparisons and they'll always work for normalized numbers. If users need to use them with raw input that contains numbers, they can run it thru `to_number(...)`
