### ISSUE TITLE
Waits for different media types

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#421]
Needed for Surveyor 2

**Comment by rowanseymour** [comment]
Currently RapidPro surveyor flows add 4 wait types to `RuleSet`:

```python
TYPE_WAIT_PHOTO = "wait_photo"
TYPE_WAIT_VIDEO = "wait_video"
TYPE_WAIT_AUDIO = "wait_audio"
TYPE_WAIT_GPS = "wait_gps"
```

Those are instructions to the surveyor client to record a photo/video/audio/gps but at some point they have to become messages, which presents 3 possibilities:

1. They are distinct wait types which require distinct resume types and remain distinct types  (e.g. `image_received` events) until RapidPro has to save things in the db and converts them to `Msg`. `@input` can be different types of things.
2. They are distinct wait types which require distinct resume types and the resume converts them to messages (i.e. the usual `msg_received` event). `@input` is always a msg.
3. They are a regular msg wait (meaning "wait for a message with an attachment of type image.. etc"). `@input` is always a msg.

I think I'm leaning toward 3 and it would mean just adding a field to our existing `msg` wait, e.g.

```json
"wait": {
    "type": "msg",
    "require_media": "image",
    "timeout": 60
}
```

It does make me wonder about making it easier to ask for the same thing in a regular messaging flow - currently users need to look in `@step.value` which contains attachment URLs and manually check for something looking like a correct image URL. It would be great to make this easier but I don't see any obvious way to consolidate asking for media in surveyor and asking for media over regular messaging. In the latter case you have to accept any msg and use flow logic to re-prompt the contact until you get the media you want. Maybe we could make that easier with new rule types?

**Comment by nicpottier** [comment]
Ya, I don't think 1 or 2 work, because you can get resumed with something of a different type. IE, you could be waiting for an image, but they could send text, and that needs to properly resume, but fail through a router and get the retry message. Maybe the wait should be a wait for "input"? And then it is up for the router to determine whether the last input matches what is expected?

**Comment by nicpottier** [comment]
> It would be great to make this easier but I don't see any obvious way to consolidate asking for media in surveyor and asking for media over regular messaging. In the latter case you have to accept any msg and use flow logic to re-prompt the contact until you get the media you want.

Are these that different really? I guess we could pass back the "hint" of what media we want back in the resume in the wait we pass back, but I think the engine needs to deal with being resumed with something that doesn't match just like any other input.

**Comment by nicpottier** [comment]
Just for historical completeness, our decision in the end is that `msg_waits` are not specific to the type of input, but CAN provide hints to the client as to what type of message is desired in the resume. But it is up to the flow author to validate the type of that input if desired. IE, the hint is not a contract at the engine level, only an attribute to help clients provide the desired type of input. In the case of the surveyor because we have full control of the client, we will use the hint to only allow the user to respond with a message that meets the hint. (and therefore our flow design will not include validation of that type)

**Comment by rowanseymour** [comment]
Added in #430
