### ISSUE TITLE
Error codes for events?

### ISSUE THREAD

**Issue by ericnewcomer** [nyaruka/goflow#44]
We may want to give callers more granular control on how to reliably handle error events. For example, it may be useful to take a different action if the flow blew up due to a runtime cycle.

**Comment by rowanseymour** [comment]
It might be sufficient to communicate back to the caller the "class" of error. For example I see at least 3 different error "classes":

1. An error may have occurred but the show goes on (e.g. expression evaluation, maybe user didn't mean for something to be an expression)
2. An error occurred so this action is being skipped but the show goes on (e.g. your webhook URL was an expression that evaluated to an empty string)
3. An error because your flow can't be run (e.g. this test doesn't exist)

**Comment by rowanseymour** [comment]
Just noting that the way we're currently going with this is that there are essentially 4 kinds of error:

* **Server error**: Internal things, e.g. server runs out of memory. 
  - Returned to the caller as an error response with message (500)
  - Caller can retry the same call later
* **Request error**: These are things that we will try to catch at the validation stage of a request, e.g. structural problems in the flow. 
  - Returned to the caller as an error response with message (400)
  - Caller shouldn't retry the same call
* **Fatal runtime error**: These are things which we can't detect at the validation stage but also can't continue from, e.g. loop detected
  - Session and run are given status=errored and event log contains an error event
  - Caller can't resume this session
* **Non-fatal runtime error**: These are more things which we can't detect at the validation stage but can safely ignore and continue from, e.g. template evaluation problem
  - Event log contains an error event
  - Caller can ignore or surface the error to the user (e.g. in simulator window)

**Comment by rowanseymour** [comment]
Closing this as much has changed. We no longer have a flowserver - mailroom is calling goflow directly so there's no scope for server/request errors.

But we do have `error` and `failure` events (fatal error that prevents flow contiuation)
