### ISSUE TITLE
Should goflow send emails?

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/goflow#537]
For discussion, but feels more right for me, if for no other reason than:
  1) you could potentially split based on whether you succeeded in sending (not something we have to add but kinda fits with webhooks)
  2) having the error message in the session sure would be nice, right now not quite sure where to stuff this
  3) it sure seems similar to webhooks / resthooks / cash transfers

  https://sentry.io/organizations/nyaruka/issues/903115246/?project=1281372&referrer=alert_email&statsPeriod=14d

**Comment by rowanseymour** [comment]
My only hesitation is it would definitively answer (no) the age old question of is email a channel, is sending an email like sending a message... so we just need to be sure we've got that right.

**Comment by nicpottier** [comment]
I don't think that's necessarily true. If emails were messages they would be messages and we would probably still have an email action for setting subjects, CC'ing etc.. (also I really never want emails to be messages, please no)

**Comment by rowanseymour** [comment]
Sure sure but goflow would still be sending back an `email_created` event (vs `email_sent`) and mailroom would be asking courier to send it and any error would be a channel log etc

Not at all advocating for sending emails like messages.. but what's the major reason against that?

**Comment by nicpottier** [comment]
No I think that makes sense, my point is that I think those are distinct things. One is email as a channel, and ya, that creates events that get turned into messages and passed to courier etc.. The other is email as an action / reporting task, and on that one I feel it fits more into a goflow task.

**Comment by rowanseymour** [comment]
Yeah certainly true that email destinations tend to be users rather than contacts.

Side note to think about then... email credentials would need to be passed to the goflow. Maybe time to think about how email, transfers, NLP could be generalised into something like "providers". That is, a session can configure a provider for email, a provider for NLP etc.

Just trying to think how we can avoid having the environment turn into a smörgåsbord of settings for all sorts of things.

**Comment by nicpottier** [comment]
Oh I'm totally down for any kind of abstraction over that config stuff. I think that makes a lot of sense. To be clear it would still just be a bag of config though right for those? IE, all the implementation still has to live in goflow right?

**Comment by rowanseymour** [comment]
Yeah more thinking about the abstraction between parts of the flow definition and the implementation of these things. For example, the `send_email` and `send_airtime` actions are kept generic and relatively dumb, and they defer to the email provider and the transfers provider on the engine.

Like wise the `has_intent` (?)  router test doesn't know anything about NLP but defers to the NLP provider on the engine.

So instead of our current approach with TransferTo where the action and router test are off in their own extension - the action and test become generic and part of the core spec - and the extension provides a "airtime provider" to make it work.

**Comment by rowanseymour** [comment]
Revisiting this now that we have an architecture for "services"

* `send_email` would defer to an email service to actually send the email
* would generate a `email_sent` event rather than a `email_created` event which could contain responses from the email server etc 
* mailroom might handle that by saving something akin to a channellog for SMTP

**Comment by rowanseymour** [comment]
Added in https://github.com/nyaruka/goflow/pull/807
