### ISSUE TITLE
string and array specific LEN

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/goflow#575]
I think these should be different methods. We've done a good job of making everything unambiguous in expressions and I think we should stick to that for length. Maybe `len` is the typical case of string length and `array_len` is the array case.

As to the point that we have `JSON` and `Format` that take anything, I think for those that is a feature rather than a bug. The user is telling us do the best of formatting this value regardless of what it is, I trust you, so I think keeping those as having type specific behavior is ok / desirable.

**Comment by rowanseymour** [comment]
After much deliberation offline we may have agreed on `length()` always being text length and `count()` only working for array-like things, groups, urns JSON etc. Since everything is convertable to `text`, `length()` can never fail. `count()` however would error if given anything which is not array-like.
