### ISSUE TITLE
`@results.name` should be the value

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/goflow#644]
Eric and I spent Friday building flows and we both really really hated having to do `@results.name.value` to reference values. This becomes especially crazy when referring to parent or child results, `@parent.results.name.value`

I'm quite afraid that we are going to drive people nuts with this and I think we should figure out how to tweak it. Another argument for it is that `@fields.name` DOES resolve to just a field value, so having `@results.name` act differently is going to be an ongoing source of confusion.

I think we have a few different directions we could go to make that work:

1. We could make `@results` be just the value and only keep category within `@run.results`. One problem here is with `@parent` and `@child` which don't have the full `run.results` as you do in the current flow, so we would have to figure that out, either by adding another sibling to `results` (`run`?) in `@parent` and `@child` or do something else.

2. We (re)introduce the concept of a `__toString__` (can be whatever as a name, that's just javascripty) element on objects. If that key is present, that is used when stringifying an object. In all other ways objects remain the same. This lets us reintroduce some shortcuts but does also reintroduce magic of a sort, though it would be at a type level (objects can define their stringification) rather than a per type level. So `@(json(contact))` would still give you the full JSON of the contact, but `@contact` would give you what is in `__toString__` instead.

   This may be a reasonable way to remove / simplify the `format_` methods we have that are specific to RapidPro types as well. (ie, maybe we can get rid of `format_results` and `format_input` which then makes Excellent that much more generic)

I lean heavily towards 2) because I feel it makes Excellent more powerful in general and easier to scale in the future. It also has the somewhat neat property of allowing you to do neat things in your webhook results if you want. (IE, ducktape.io could populate these keys too in its responses)

Most importantly it reintroduces the ability to make things more user friendly for users which should be our #1 priority.

Now I guess the question to @rowanseymour is whether that introduces too much ambiguity in arguments elsewhere, where we would suddenly lose information with a parameter like `@contact` that gets stringified when we really want it to be the full dictionary. It seems to be that we are never relying on the stringified version of objects as it is as a parameter to anything (IE, this would already be a problem if we were), so as long as we are stringifying only at a last step then it shouldn't be weird.

@ericnewcomer

**Comment by rowanseymour** [comment]
So I'm not particularly wedded to context non-leaves resolving to JSON like objects but I am a little perplexed because:

1. `@results.foo.value` is no harder to write than `@flow.foo.value` (in the old editor it's nearly impossible to write `@flow.foo` due to the way auto-complete works)... so I don't understand why we've suddenly decided that is an unacceptable user experience.
2. we've remarked many times that no-one can remember what `@flow.foo` is - is it the value or category or input. There was something useful about forcing the user to be explicit.

Obviously the `@parent.results.foo.value` is a bit more annoying but hardly the end of the world. That said...

I have had my doubts about dumping out full objects by default because it feels like we're using the very limited space of a text entry box to solve something that should be solved by better editor tooling, i.e. a shiny new context explorer which let's the user see exactly what is in the context and how to reference each part of it.

I think if we say `@results.foo` is allowed to have some magic then we would want to be consistent and revert to using single values for _everything_ else in the context like `@contact`. I like the idea of a magic property because we still keep all the wins of everything being a single simple type - we're just introducing a new behavior to that type. `format_input`  and `format_results` have definitely felt a bit dirty and won't shed any tears removing them.

Maybe `__default__` is apt given how much Excellent 2 is feeling like Excellent 1 these days and also that would leave the door open to this being a typed thing. For example we did for a while have `@fields.foo` resolving to a typed thing whilst `@fields.foo.text` resolved to the `text` representation. You'd implement that as a `{__default__: XNumber(37), text: XText("37yrs")}`, and it just means that the first step of converting an object to another type is looking up the `__default__` property if there is one... like what we were doing with `Reduce`.

**Comment by nicpottier** [comment]
Ya, I mean we were all on board with having those require full leafs but then we started using it and it sure felt painful.

Poking flows on our installs I see almost everyone `@flow.foo` not `@flow.foo.value`. Yes, we make this annoying for the user but they really want that to be the value. (and this is why we run into problems with trailing periods in values is because people press enter to select the value in the old autocomplete then space to make the autocomplete disappear, which leaves a period turd) Maybe if we doubt that we can examine our actual flow definitions and figure out the percentage but that was across a dozen accounts or so and I actually never saw anybody using `.value`, only `.category`

I have no objections to adding other `__defaults__` to branches in the tree.

**Comment by rowanseymour** [comment]
That's interesting. Could be as simple as that being the way we do it in docs or sample flows so users aren't sure what `@flow.foo.value` is but they know `@flow.foo` is correct.

I do think it would be weird for `@results` to behave differently to other parts of the context so I think this is decision to re-adopt default values consistently throughout the context.

Why does make me wonder if the `{foo: bar}` rendering of objects is a thing anymore. If the only objects that don't have that are being pulled from JSON webhooks.. then maybe those just render as JSON.

**Comment by nicpottier** [comment]
I think current rendering of objects stays the same, if for no other reason that it is consistent with array rendering then.

**Comment by rowanseymour** [comment]
Heads up that we also lose pretty formatting of objects. If the `format` function uses the default, e.g. `format(result.age) -> 37` `format(contact) -> Bob`, then there's no way to actually format with all the properties if that is what you actually want.

**Comment by nicpottier** [comment]
Right, we lose pretty formatting of objects with `__default__`s, but we still get it for others ya?

I think I'm ok with that, we can always add in a `format_object` or something later if we decide we do want to expose that and they will still see the structure with just `json(contact)` right?

**Comment by rowanseymour** [comment]
I can convince myself that's ok because that feature didn't exist two weeks ago.. I am a bit sad because it's pretty 😢. But yeah we could add something like `yaml(contact)` in the future or whatever... and anything that makes more like like the old world certainly helps with the "just get it out there" priority.

Don't we think all objects will have defaults? They all had defaults until recently so I'm working on the assumption that I should be putting all those defaults back to be consistent.

**Comment by nicpottier** [comment]
Webhook responses (likely) won't. It seems like there could be parts of the tree that don't as well. I'm not particularly tied to us having defaults everywhere in our context but if you feel strongly about it go for it.

**Comment by ericnewcomer** [comment]
I think this first version needs a replacement for people using @flow in emails. That can certainly be a special function, but we won’t be able to migrate after we launch without it.

**Comment by nicpottier** [comment]
Ya, for sure we need replacements for `format_results` and `format_input` .. just wasn't sure whether we needed others apart from `results.foo` but I'm done for whichever.

**Comment by rowanseymour** [comment]
Addressed in #651
