### ISSUE TITLE
has_number test fails with values like `.25`

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/goflow#657]
Seems like that should work no?

**Comment by nicpottier** [comment]
Actually, this seems to be parsing, but it is parsing as `25` instead of `.25`, likely because of how we tokenize. This founds familiar actually and maybe we have required the leading zero in the past but I wonder if that is really right?

**Comment by rowanseymour** [comment]
I am getting that weird deja vu feeling that we did have this conversation once before and decide to require initial zeros... 

I actually replaced the old tokenizing parser for numbers recently with a good ole regex so it would be pretty straightforward to tweak things so that `\W\.` is interpreted like `0.`, i.e.

`...25` -> `25`
`Yes.25 of them.` -> `25`
`it's .25` -> `0.25`
`.25` -> `0.25`

**Comment by nicpottier** [comment]
Ya, I feel like for users, then asking them to prepend `0` to decimals in expressions is fine, but asking contacts to do that is just confusing. (including to Eric and I when making bets in Blackjack)

So I think we should change to parse decimals correctly when there is no leading 0.
