### ISSUE TITLE
Awkward to get at webhook body

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/goflow#663]
So we currently only include `extra` on the full context for results, meaning you have to do something like `@run.results.webhook.extra.response[0]` to get at something vs `@results.webhook.extra.response[0]`

Do we want that to be easier? I suppose the argument against having that in `@results` is that these are the same simplified results we see on `@parent` and `@child` so being consistent on what is available there makes sense. (I agree with that)

Should be have something similar to our old `@extra` though that is just the last webhook body? IE: `@webhook`? That would shorten the above to just `@webhook.response[0]` which sure seems more reasonable.

**Comment by nicpottier** [comment]
@ericnewcomer

**Comment by rowanseymour** [comment]
It should definitely be on `@results` the same as `@run.results` - the reason I punted on adding it there previously is because that would change the default webhook payload which is using `json(results)`, so we have to decide if 1) we want potentially big webhook payloads (payloads in payloads!) appearing there 2) we want a func like `extract_dict` that excludes a named field.

Re having a `@webhook.response[0]` - I don't love treating webhooks as a special case here since extra can come from various places, so if we did go that route I think I'd lean toward `@extra.foo` where `foo` is the last extra. But I don't hate `@results.webhook.extra.foo`. `@results.webhook` is the natural place to look for that since that's where everything else relating to that webhook result is.

**Comment by nicpottier** [comment]
I though we already had an `extract`, did we lose that? It feels slightly nutty to be able to access the webhook results of your parents / children but I guess that's all really just captured in the giant session blob anyways so 🤷‍♂ 

To be clear I wasn't proposing putting all extras in `@webhook` just the webhook ones. I could go either way as to whether resthooks populate that though likely would lean against it.

It just seems to be that this is another case where we are making things quite a bit more awkward for users who used to just be able to do `@extra.foo` and now need to do `@results.my_webhook.extra.foo` (if we did add it to `@results`).

Calling out to external APIs is a pretty big thing in RapidPro, I'm not bothered by that being a special / optimized case.

I guess I could be convinced to have an `@extra` that basically is always the last `@extra` that is written. Would that get cleared when a result is written with no `extra`? Nice thing there would be that in most cases people wouldn't have to relearn how `@extra` works and that we'd be consistent in the naming of those attributes in `@run.results` and elsewhere.

**Comment by nicpottier** [comment]
@nyaruka/nyaruka thoughts?

**Comment by rowanseymour** [comment]
We still have `extract_dict` - which we could actually use here to get `json(result.foo - extra)` for the default webhook payload. I just meant we don't have an easy way to exclude rather than include named object properties.

Users will probably use whatever we put on the call_webhook UI.. which is a bit out of date right now:

<img width="636" alt="Captura de Pantalla 2019-04-30 a la(s) 15 56 51" src="https://user-images.githubusercontent.com/675558/56971136-9ad20b80-6b60-11e9-8e00-3648c61a2df3.png">

I don't think we'd recommend `@extra.foo` over `@results.my_webhook.extra.foo` here, since the former is more likely to come back to bite users when they have more than one webhook, so then I just wonder who would discover and use `@extra`. If we add `@webhook` then we have to explain to users that it only has the parsed JSON and that status code etc live elsewhere.. I feel like `@extra` would be easier to explain to new users.. potentially confusing for old users since it's subtly different in that it doesn't accumulate results.

**Comment by nicpottier** [comment]
Ah, I see, for that particular case (recreating webhooks) seems like explicit inclusion is better than exclusion anyways. (IE, the odds of us forgetting to add to an exclusion seem rather high, already we have `__default__` in there don't we?)

So I think the problem with an `@extra` is that it is so easy to be overwritten. Having built some flows now I think the big takeaway is how great the set result action is, it just makes things way easier when building complicated flows. And I see a very high probability of someone calling a webhook, then having like three set result actions immediately afterwards that are basically saving away parts of that webhook in the flow. Problem is that if they are using `@extra` then only the first of those will work, as that set result action will overwrite `@extra` with a blank value. (if I'm understanding you correctly)

So that brings me back to preferring `@webhook` being the `@extra` of the last webhook action. It is obvious (more obvious than `@extra` has ever been) and it is more obvious to the user that calling a new webhook in a flow is going to overwrite the previous webhook response.

Users can still access previous webhook responses through `@run.results.foo.extra` if they like. It also keeps the result summary a summary, which I think is more correct as well, and then keeps that consistent across parent and child flows.

I guess the question is what is the real downside to that? The concern you have @rowanseymour is that that is over specializing the webhook case? (to which I would respond that's desirable)

**Comment by ericnewcomer** [comment]
Chatted a bit with @nicpottier in the office on this, and just wanted to say that I concur a dedicated space for webhook results is not offensive to me. While it's not as tidy as responses being tucked away in results, it's more more user friendly to have a response body at the ready under `@webhook`. Users aren't typically going to be looking at status codes, etc since we give them branching for that already.

**Comment by rowanseymour** [comment]
I just think it's easier for users to understand that a given webhook's results are at `x.y.z` than the last webhook JSON will be at `x` but not the status code etc. When we're trying to balance consistency and brevity I think we lean in different directions. 

So the downside for me is that once again the context ends up with same things different places (`@contact.fields` vs `@fields`) - or subtly different things in similar places (`@results` vs `@run.results`). All of that makes expressions less simple for users.

Would we add a field to results so we can identify which ones were created by webhooks and then map that to `@webhook` in the context?

**Comment by nicpottier** [comment]
I think the philosophy I tend to use is to make the common thing as easy as possible but make the complicated thing possible. And yes, in some cases that does lead to repetition. IE, if we can make changes that make the 95-99% use case be significantly easier, then we should, because that's a benefit to our users. If they eventually hit a wall using that easier path then they level up and discover how to do more complicated things.

That's the thinking behind having `__default__` and `results`, `category` vs `categories` etc.. 

Now we can argue whether that's the right philosophy or not from a product design perspective, but I think we've done pretty well to this point with those kinds of decisions. The place where we have gotten in trouble in the past is the ambiguity of `extra` in that it was so many different things and append-only.

So to me a top level `@webhook` does satisfy the 99% case for users, most will never have to understand more than that, and it creates a much simpler thing for them than having to understand that `@results.foo.extra` even exists. (status code is a great addition in new world for sure, but again people just don't use that in the common case)

**Comment by rowanseymour** [comment]
Anyways, have you thought about how to implement this? I hate the idea of duplicating webhook payloads in yet another place on the session blob.. can we flag results as having come from a webhook and then map the last one to `@webhook`?

**Comment by nicpottier** [comment]
Can we look backwards in the run events so the last webhook event (is the body there?)? Seems it would have to be something like that or alternatively sorting results by `created_on` and ya knowing whether it is a webhook or not?

**Comment by rowanseymour** [comment]
The whole response is on the event so guess you could just parse that.. saves changing anything on the result
