### ISSUE TITLE
multiple-value uuid.NewV4() in single-value context

### ISSUE THREAD

**Issue by Kirembu** [nyaruka/goflow#675]
```
$ go install github.com/nyaruka/goflow/cmd/flowrunner
# github.com/nyaruka/goflow/utils
go/src/github.com/nyaruka/goflow/utils/uuid.go:22:24: multiple-value uuid.NewV4() in single-value context

```
https://github.com/satori/go.uuid Seems to have changed their UUID generation API.

**Comment by rowanseymour** [comment]
I'm curious how this happens because we're supposed to be pinned to v1.2.0 of that library..

But it seems we shouldn't even be using this library anyway, as it's got some critical flaws and it's no longer maintained: https://github.com/satori/go.uuid/issues/84. So I'm going to switch over to https://github.com/gofrs/uuid

**Comment by Kirembu** [comment]
> I'm curious how this happens because we're supposed to be pinned to v1.2.0 of that library..

I had manually installed the dependencies. I'm pretty new to go. I'm familiar with Python but I'm learning by ear with this repo.

Thanks for the heads up. I got things working by sticking to the pinned versions. Works great now.

**Comment by rowanseymour** [comment]
Have switched to the gofrs library in #676
