### ISSUE TITLE
`[]` can't be used without `@()`

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/goflow#701]
That's pretty subtle. Is it really necessary?

**Comment by rowanseymour** [comment]
Something to consider, is if we allow `[?]`.. what do we allow as the `?`...

```
@contact.urns[0]
@contact.fields["age"]
@contact.urns[4 / 2 - 3]
@contact.urns[fields.fav_urn_index]
```

I think really it would have to be any expression.. which is probably doable by balancing `[` and `]` (and ignoring those in string literals) same way that we do for `(` and `)`

**Comment by nicpottier** [comment]
Ya I think the strong argument that it needs to be anything is that otherwise there's no dynamic way to look up an item in a dictionary right? You can't use dot notation with a variable, this unlocks that.

(is it currently only digits?)

**Comment by nicpottier** [comment]
Although we are talking about what works WITHOUT `()` .. and it does seem slightly nuts for our parser to be able to do something like `@contact.urns[4/2-3]` without that. I would be ok with saying only simple literals work if that is a simplifier.

**Comment by rowanseymour** [comment]
To be clear we currently allow any expression inside `[]`, but we don't allow `[]` after an "identifier" (not a full `@( ... )` expression). And also it's the lefthand side that dictates whether it's a named property or numerical index lookup.

From an implementation pov, I don't think it would be much harder to support `@foo[bar]` where bar is any expression, than saying `bar` has to a single string or number. Parsing the `[...]` bit is pretty much the same balancing trick as parsing `(...)`.

It just needs to be clear to the parser and the user where the expression begins and ends. We'd probably also need to support multiple `[...]` lookups in same identifier, e.g.

```
@webhook.results[1].values[3].name
```

Which I think I'm cool with but it would make me want us to revisit our decision that `@upper(contact.name)` needs to be `@(upper(contact.name))`. We did that to avoid collisions with other uses of `@` such as email addresses and twitter handles.. but it seems simpler to explain to users that `@` is always an expression and `\@` is not, than `@` might be an expression depending on what comes after it.

**Comment by nicpottier** [comment]
Remind me of our rules again? I thought for the case of say `@bar.baz` we did echo out `@bar.baz` while in the case of `@(bar.baz)` we didn't. Am I remembering that wrong?

I'm not sure users are differentiating between what they think an expression is vs just a variable. I think the distinction is more likely, "when I call a function I use `@(upper(foo.baz))`", when I'm just referring to a value I use `@foo.baz`.

So to me, I do feel like our current balance is about right, that is the easiest things can just be `@foo.baz` and leveling up to `@(upper(foo.baz))` isn't too big a burden while also making the surface area of what people have to escape (thought escaping was `@@`) still small.

Happy to be convinced otherwise though if other peeps disagree.

**Comment by rowanseymour** [comment]
Oh you're right, escaping is `@@`!

`@bar.baz` is never even parsed as an expression because we only parse identifiers with a top-level key of "child", "contact", "fields", "input", "legacy_extra", "parent", "results", "run", "trigger", "urns", or "webhook"

`@contact.foo` is treated exactly the same as `@(contact.foo)` - it's not echoed out again and there's an error event visible in the simulator.

I've occasionally had to tell users to add extra parentheses around something like `@upper(...)`. I'm not necessarily arguing that we should change that... just that _if_ we say a complex expression like `@fields[upper(results.gender)]` doesn't require outer-parentheses, it would seem pretty counter-intuitive that `@upper(results.gender)` does.

**Comment by nicpottier** [comment]
Ok, so if we expanded to support all the method names as things we would try to parse at the top level wouldn't we then greatly increase the odds of collision there (and silent removal from the message)?

I guess I agree that `@fields[upper(results.gender)]` should not work. But `@fields[results.gender]` should. To me the line is function calls. You call functions, you use extra parentheses.

**Comment by rowanseymour** [comment]
Re allowing `@upper(contact.name)`.. I'm on the fence. Arguably it's shit work to have to escape regular `@` characters, but arguably it's also shit work to have to wrap simple expressions like that in outer parentheses. It also makes the expression harder to read (you have to balance those parentheses) and perhaps it would be simpler for users to understand that `@` is always an expression. Remember that if they're typing `rowan@` they're going to see an auto-complete drop down after they type the `@`.

Re allowing `[..]`. I'd push back against that on two fronts...

Firstly I think from a user's point of view, "does it contain a function call" isn't an obvious way to distinguish between simple and complex expressions. Imagine a user writing `@fields["foo" + results.gender]` ... it's complex (and contrived) but it works in the simulator, but then as soon as they add a call to `upper`.. it just ceases to be an expression. Just stops being parsed without any visual indication as to why.

Secondly from a technical point of view. Currently template evaluation is a two step process. The scanner looks for expressions in the template, the parser evaluates those expressions. The scanner gets to be relatively dumb and basically counts parentheses to find balanced sequences, and knows nothing about the actual Excellent grammar. If went the route of everything except function calls is an valid expression, then either
  1. The scanner would have to parse the expression.. sorta ceases to be a scanner at this point. Things like our Javascript expression extractor would no longer work. 
  2. The scanner's role would have to become find things that _might_ be expressions, pass them to the parser, it decides if it's not actually an expression, scanner. Again you can't extract expressions without doing full parsing.

Sometimes I wish we were using something more like `{{...}}` for complex expressions because that would more clearly separate the syntax of expression boundaries, from the syntax of the expressions themselves. Parentheses currently does both. But that's a whole different discussion and that ship has sailed.

**Comment by nicpottier** [comment]
Ok, can see the argument towards parsing being more complicated. Let's allow arbitrary in `[]` but for now stick with `@()` for the other cases. We can always expand that later if we want.

I still think `@` is a good thing honestly, it has drawbacks but for the common case I think it does make it easier for the end user, so no regerts on that front.

**Comment by rowanseymour** [comment]
To be clear my issue isn't with the `@` part but the parentheses in `@()`. If I had a time machine I'd go back and persuade us that `@{...}` is a much superior option because `{` is distinct from the expression syntax itself.

I think these two broken examples demonstrate the advantages pretty succinctly:

```
@(upper(left(foo, 5))
```

```
@{upper(left(foo, 5)}
```

Even without syntax highlighting, it's easer to see in the second case that the expression is missing a final closing parenthesis. 

But more importantly.. the first one isn't even handled as an expression. Because expression extraction relies on balanced parentheses, the scanner doesn't extract it, and the user sees it as is in the output with no explanation as to why or what is wrong with it.

However in the second case, the scanner (which gets to be even dumber) extracts anything inside the `{...}` and passes it to the parser. The parser can provide a useful error message like `expecting ) after ", 5)"`

**Comment by rowanseymour** [comment]
Been pondering on this a bit more and I even had a user ask me the other day why they couldn't do something like `@webhook.results[0]`. Now obviously we could take that to mean we have to add support for identifiers ending with `[0...9]`.. but then the next user question will be why identifiers can't end with `[<expression>]` or `@foo[<expression>].thing[<expression>]` and so on.

So I think the key here is identifying what would be the clearest line in the sand between expressions that don't require outer parentheses, and those that do.

At the two extremes (not advocating for either of these) we have:

 * Always need parentheses! Annoying to type but no-one would wonder again how to add an expression
 * Never need parentheses! The scanner extracts anything which is a syntactically valid expression, i.e. there's no such thing as an expression with a syntax error, and no error messages about syntax errors. Good luck getting your expression completely right first time!

In between we have various options...

* `(contact|flow|...).bar.thing` any simple context path reference that starts with a valid top-level context property (`contact`, `flow`, etc) [the current line in the sand]
* as above but can end with `[\d]`
* as above but each key can end with `[\d]`, e.g. `@webhook.foo[1].bar[2]`
* as above but each key can end with `[<expression>]`, e.g. `@webhook.foo[results.lookup]` (what I proposed above, scanner doesn't parse `<expression>`, just counts brackets and tries to balance them)
* `@[^\s]`.. maybe anything without a space, being careful to exclude punctuation like `@contact,`

For me the first option really seems the clearest. And implementation wise - by far the simplest.

So then I start wondering if we shouldn't allow `@contact.groups.0`. If I recall right, there were two reasons to disallow this:

 1. we had objects in the context that behaved like arrays and like objects, so for `foo.X`, it was the right-hand side (the type of `X`) that determined is this a property lookup or an array index. So it could be ambiguous if X is a property called `"0"` or the array index `0`.
 2. `foo.0.2` was grammatically ambiguous

I think 1. is no longer a problem - everything in the context now behaves like either 1) a primitive type 2) an array 3) an object. So I think the left-hand side of `foo.X` can reliably determine whether it's an array lookup or property lookup.

I think we can fix 2. by introducing integers into the grammar.

**Comment by nicpottier** [comment]
I like the out of the box thinking! I thought another reason was ANTLR hell of some kind or another. If not then I agree that this is the clearest and simplest solution.

**Comment by rowanseymour** [comment]
That's what I meant by grammatically ambiguous but thanks to my historical policy of not documenting decisions.. I don't remember exactly what the problem was.. and looking at it now it seems workable.. won't know until I try it again.

**Comment by chris-erickson** [comment]
Happy to leave some thoughts here, though I can't quite pin down what proposals we're debating.  Perhaps we can back up and discuss why what I'm struggling with doesn't work, and then I can provide ideas on how we might resolve this from an idiot's perspective (me):

1. Webhooks saves results to `My Data`
2. `Result: @results.my_data.extra[0].name` in a Send Message responds with `<my data json result here>[0].name`

Data in webhook looks like
```json
[
  {
    "name": "The name 1"
  },
  {
    "name": "The name 2" 
  }
]
```

**Comment by nicpottier** [comment]
It doesn't work because of the issue title. :) It would work if you did `@(results.my_data.extra[0].name)`

Reason we don't support `[]` without `()` are above but mostly boil down to it then becoming hard to draw the line of what is supported in `[]`. Current top proposal is to reintroduce using numerics in dot notation which would allow `@results.my_data.extra.0.name` as that doesn't muddy the line as much.

**Comment by chris-erickson** [comment]
🎉 there we go!  So, I think the dot notation is desirable as it makes that path pretty obvious.  It's a little odd, but learnable.

I love the idea though of a new character to delineate where an expression takes place, it's reminiscent of python f-strings and javascript template strings but I'm sure that's way more invasive.
