### ISSUE TITLE
Error when a webhook is too large should include URL of webhook

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/goflow#814]
Currently if we get a webhook response that is larger than 10k we don't process it. That's fine but we don't have anything in our session that logs what URL was called.

Would be nice to have that present.

Also, not sure if this is a migration thing but when we get that kind of failure we also get knock on errors because the expected result isn't present, that's confusing for users:

<img width="768" alt="Screen Shot 2019-12-19 at 9 59 59 AM" src="https://user-images.githubusercontent.com/168067/71197424-6d001b00-2246-11ea-9923-296813c180c1.png">

**Comment by rowanseymour** [comment]
Hmm me thinks both of these are the same problem - we don't save a webhook result under certain error conditions. If the response is 400+ or we timeout we still have a webhook result - a record of the URL and something to route on. But exceeding the 10,000 byte limit is just an error.

We've designed airtime transfers and classification actions to _always_ save a result and it seems we should try to do the same with webhooks.

**Comment by nicpottier** [comment]
I do wonder whether we should reconsider our size approach. Realize we currently do our limits because we log the entire payload and put the entire thing in the result, but maybe we should just trim the saved payload and do something similar to the "first n keys" we used to do in the old world? Or maybe you get to access the webhook full body in the same sprint but not in future ones if over a certain size? That may be a bit subtle but this is kind of an annoying limitation, especially at 10k. 

It makes sense when you consider we save the whole thing to the session but not really to a user and they just want their thing to work. (in this particular case they also did not have access to the API (it is an external one) so asking them to reduce the size of the returned payload is a big ask)

Could trimming take place at the mailroom side of things maybe? (with a log entry that we did so?) So that in the sprint itself you get the whole shebang but we end up only logging and saving to the session some piece of it?

**Comment by rowanseymour** [comment]
Something to consider is that the payload ends up being recorded in 2 places in the session:

1. Parsed as extra on the result 
2. As the response dump on the `webhook_called` event

The latter is just for logging so I think it would be fine to just trim that to X characters. We currently have a `body_ignored` flag on that event to record when the body isn't a type we want to read.. ideally that would be something like `body_state = full|trimmed|ignored`

The former is where things get tricky but I agree the current situation sucks for users who are trying to pull data from endpoints they don't control.

Making the result only temporarily available seems potentially confusing for users and I don't love the idea of mailroom modifying sessions. I suppose we're talking about something like mailroom clearing extra on the result? Or a flag on the result when it's set so that goflow knows to clear it.

The downside of key trimming is we can't even be sure that 1) we're leaving the bit of the payload the user actually wants and 2) the output is as small as we would want it to be.

What if the user could provide an advanced setting on that action that controls which part of the payload we keep as extra? An excellent expression?

**Comment by nicpottier** [comment]
I really wonder how often people use a webhook result past the sprint it was called in, I would gander not too often. And additionally I would say anybody who DOES want to access other things can do so by saving a result explicitly.

So if we were designing this functionality from scratch today then I think I would argue towards `@webhook` being the only way you can access webhook results and that is only for a webhook you just called. And our result doesn't save the webhook response in extra, just the status etc.. 

Users can then use all the other tools we give them to save parts of the webhook they are interested in. We could maybe have a field that is not serialized on the `webhook_called` event then that Mailroom uses to insert webhook logs. (which it can choose to trim or not, that's up to the implementation)

That feels the most sane behavior from a GoFlow perspective, in that we are not longer writing gigungous webhook responses in our event lot which has always felt pretty bananas.

I think I could imagine us migrating to a model like this where old users are grandfathered to have extra set but new webhook actions work in the way above. Again, I would bet a tiny minority of users ever look at webhook results after a sprint so even for new flows most users would never notice the difference.

That is basically the same as your approach except it is being explicit about making the user choose to save a webhook body if they want to refer to it in the future, which I prefer because:
  1. Its less junk in our session for the default case
  2. It uses the tools we already have ("Save Result Action") instead of adding a special feature
  3. It encorages the use of `@webhook` which I think is more natural than the more verbose `extra` approach anyways.

**Comment by rowanseymour** [comment]
I wonder also but I also can't forget how impressed we were with ourselves for adding a new way for users to access all the different webhook calls in a run forever 😁 

I think regarding the events, I'd be fine with jut saying it's a configuration option on the engine. We also want to limit what we save to the DB in mailroom. If other deployments want to log and save megabyte payloads that's up to them. 

I like the general principle of "you want to store some data from your bloated webhook call then you decide what you want to save"

I also think we may have overstated the utility in having every webhook result kept around.. `@webhook` seems to strike the right balance between keeping everything and bundling everything in `@extra`.

Maybe for backwards compatibility we continue writing small payloads to `extra` on the result?

**Comment by nicpottier** [comment]
I'd say downside to only writing "small" results is that then behavior may change in the future if say their results start getting larger. (that's actually what the origin issue was for this for a customer) So never doing so going forward would make sure that behavior stays the same for a flow for the lifetime of the flow.

**Comment by ericnewcomer** [comment]
I don’t disagree with this. I think some of the energy behind saving payloads forever was for the audit trail, which probably has some value.  That said it isn’t as important as knowing, say, how an operand evaluated at a given node.

**Comment by nicpottier** [comment]
Circling back on this after the new years I do still like this idea, though do think we probably want to log responses up to a limit for tracking purposes. I think if we treat that logging as a separate thing than the actual body of the webhook then that satisfies me from the perspective of being consistent regardless of payload size.

IE: we log the event with the first 10k or whatever of the webhook body, but the entire body is what is available in `@webhook` and the user has to save that into `@results` somewhere if they want to access it in a future sprint. The webhook body saved in the event is not available in future sprints, it is just there so that mailroom can log it and our session has some completeness.

**Comment by rowanseymour** [comment]
Ok let's put some details on this..

1. There still needs to be a limit on how many bytes we read from a webhook and recall that reading the body happens outside of the request timeout... but we can make that something like 100K... that should be enough for everyone right?
2. The webhook_called event is trimmed to 10K bytes. That's just for logging and saving to the DB in mailroom. Replace `body_ignored` with something that can also record if the body was trimmed.
3. `@webhook` points to a temporal thing on the session which contains the last entire webhook body we read. It starts off as `null` in every sprint.

I guess the only thing I'm stuck on is what to do with `@results.mywebhook.extra`.. and whether we can really just stop writing that or if it's better to keep trying to write that if the payload is sufficiently small. Bear in mind that those extras are also used to construct `@legacy_extra` for backwards compatibility.

If we did continue writing sufficiently small `extras`, then `@webhook` could still be initialized in each new sprint as the last of those. There wouldn't be any change in the current behaviour except some webhook calls would start working instead of failing.

**Comment by nicpottier** [comment]
For 1) why not make that 1M or even 10M? There really isn't any overhead anymore so why limit it? Some API calls really are that big in what they return. (this for example: https://api.weather.gov/gridpoints/EAX/40,48, 226k!) There really isn't much impact on our side of these during a sprint so I would argue towards at least 1M.

The only issue I see with making smaller things available past the current sprint is that the behavior can then change based on the result, which then makes that a really hard thing for users to understand. This issue was actually created because of a case exactly like that, in that it worked for a while when smaller than 10k but then increased over that and stopped working.

We do obviously need to make legacy webhooks work, so I do think we probably need to support that case, but my argument would be that that is just for existing flows and new flows / webhook actions would work only in the current sprint. IE, if someone has already build a webhook action then it behaves as it has, new ones behave with no limits but disappear in future sprints. Not positive how we do that though, adding a new option seems a bit ugly (ie: adding a `single_sprint: true` option) but maybe the simplest? Other ideas there?

**Comment by rowanseymour** [comment]
The odd thing about how we limit HTTP downloads is we're checking a value _after decompression_. A limit of 10MB might be actually be a transfer of 100K of gzipped JSON or it might be 10MB of uncompressed text. And to be honest I have no idea how jsonparser performs with MBs of JSON. Maybe 1MB is fine to start with but it seems to me there is _some_ overhead there at scale.. people call some really bad web-services from their flows.

I totally get that it's confusing if `result.x.extra` disappears when a payload gets too big.. but it's also going to be confusing having some flows in an org populate extra and some not. Some flows keep `@webhook` between sprints some don't.

It's a shame we don't have a "problem pane" or something like that for flows so stuff like this could be highlighted to users. Having just taught users they can use `result.x.extra`.. how do we unteach that? How do we find cases where people are referencing `@webhook` after a wait?

Seems step zero is make all our docs say "use `@webhook` and save what you need to a result". The complicated part for a lot of users is that if they want to keep blobs of JSON around in a result, they'll have to do manual serialization/deserialization with `@(json(webhook.foo.bar))` and `@(parse_json(results.saved_webhook))`

Then step 1 might be getting an idea of how many flows would break if everything switched to the proposed behavior.

**Comment by rowanseymour** [comment]
Something else to consider here is the implications now that we're returning the context with simulation requests.. which obviously includes `@webhook`.  Do we clear `@webhook` at the end of a sprint to show that it's no longer available? Or do we potentially send back 1MB of JSON in the simulator response so they can see what it was. I lean toward the former.

**Comment by nicpottier** [comment]
That's a tough one because ya, there's no way to "pause" mid-sprint so you will essentially never see `@webhook` populated which seems like a real shame from a debugging / discoverability perspective. I imagine once we have a context explorer it is going to be used a lot to "explore" what is possible and not having the webhook info in there is definitely somewhat confusing.

That said, I think that's probably the right call to start.

**Comment by ericnewcomer** [comment]
It's definitely a bummer, at least we still show the webhook response in the simulator in its own detail window.

**Comment by rowanseymour** [comment]
Still bit stumped on how to move forward with this so let's recap what we want to do... I think the key points are:

1. Events contain a trimmed version of the response for logging (10K)
2. Full webhook response (up to say 1MB) is available in expressions but not in the session blob.

Point 1 means our current approach of having `@webhook` simply point to the last of those no longer works.

Point 2 means no more writing to `@results.foo.extra` since those are part of the session blob.. which means flows reading those break 

For `@webhook`there are two alternatives...

1. `@webhook` is a transient thing during the sprint not available in the next. Liable to break flows.
2. `@webhook` is backed by something outside of the session blob. Maybe the webhook service is responsible for loading these from the DB like an asset? Maybe it writes the `WebhookResult` which can be reloaded later? 

Let's at least have a think about option 2 but assuming we don't go that route we have two backwards incompatible flow behavior changes:

- `@results.foo.extra` not being set
- `@webhook` not being populated after a sprint

Ways of dealing with that...

1. Find flows doing those things, fix them, tell users to fix them, rinse and repeat til you can just drop those behaviors. A shit sandwich for users and other deployments.
2. Introduce a flow level "legacy mode".. existing flows work as they always have.. new flows have new behavior. Problem is there's nothing visible to explain to users why two flows in their org behave differently. And we already have a "legacy mode"..
3. Make the new behavior a visible option on the webhook action. A flow with all its webhook actions using the new behavior.. exhibits the new behavior described at the start.

Unpacking 3 a bit more.. 

- It's an option on the action called `response_as_extra`
- A 13.2 flow migration adds this as `true` to existing flows.
- In the editor a user sees this on an existing webhook action as a checked option saying _Save response body to extra on the result. The body must be less than 10K._
- Any new webhook action sets that to `false`.
- Regardless of that option, responses are saved transiently to `@webhook`
- On resume sprints, `@webhook` will be reconstructed from any webhook result with extra.

Existing flows continue to work as normal, new flows use new behavior. There's a path to making an existing flow work like a new flow. Users. We can track flows using the old behavior by searching for `"response_as_extra": true`.

**Comment by rowanseymour** [comment]
Yeah I think 3) is workable in the engine. There's a small technical challenge in that we currently use webhook _events_ to construct `@webhook` because there's nothing on an _result_ that explicitly shows it came from a webhook.. but I think we can match up them using events on the same step.

Then we need to agree on the story in the editor. Is it ok if new flows don't even show the option? How do ensure users aren't still assuming the old behavior.. or do we just let them figure it out as things fail? Is there warning in the editor on webhooks that the old behavior will stop on date X ?

**Comment by rowanseymour** [comment]
I'm assuming users don't look at resthook call response bodies, right? That's all async.. We can just switch off writing those `extra` without asking?

**Comment by ericnewcomer** [comment]
Really want to see `@webhook` available in the context explorer. I think the context showing what was available during the last sprint actually makes sense, and having a navigable webhook in the context explorer is just too useful for users to not make that happen for them. Not super worried about payload side on the editor front.
