### ISSUE TITLE
Converting from Old to New Editor Loses 'Has A Date After'

### ISSUE THREAD

**Issue by putorti** [nyaruka/goflow#816]
When switching from old to new editor, I've seen my values go from `-7` or `-30` to `0` on more than one occasion, causing problems in my flows. I can't reproduce in TextIn because there's no more option to start with or return to the old editor, but it happened consistently with my flows everywhere I did it. Maybe something with the negative numbers. If fixed already, apologies.

<img width="745" alt="image" src="https://user-images.githubusercontent.com/82857/71328155-596fe100-24e0-11ea-9bde-6b2f7b99a86b.png">

**Comment by rowanseymour** [comment]
If you create a new "date after" test for `-10` days you get...

```
@(datetime_add(today(), -10, "D"))
```

If you create a legacy flow you get...

```
@(date.today + -10)
```

Which migrates to...

```
@(format_date(datetime_add(format_date(today()), -10, "D")))
```

Which the editor can't parse so the delta is displayed as `0`. Not sure it's limited to negative numbers.

Problem here is that goflow is migrating this like any other expression, so when it sees a date value like `date.today` it knows it has to wrap that in `format_date` because dates in the new world are full ISO formatted dates.

I think cleanest fix here is having goflow's flow migration treat these as a special case so that migrated flows have the same expressions as those created from scratch in the new editor.
