### ISSUE TITLE
Retries for webhook calls

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/goflow#818]
Following on from discussion at https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/rapidpro-dev/n2opcEONzZw/CUqtXANzCQAJ

We've avoided adding this in the past because ideally sprints between engine interactions should be quick and not tie up threads or database transactions. However that argument is less important now that we've moved away from python/celery.

Users are already implementing their own retry logic in flows but this is cumbersome and hard to do with proper delays. golang already does some retrying but only when it can't initially connect and only for `GET` unless the user explicitly includes certain headers in the request.

**Under which conditions should we retry?**

- Failed connection errors
- Status codes > 501 ?
- 429 "too many requests" ? see https://github.com/hashicorp/go-retryablehttp/issues/20

**How many times and with what delays?**

I think we still want sprints to be fast so my inclination is 3 attempts.. something like `try.. 3 seconds.. try .. 10 seconds.. try.. fail`

If we keep the current timeout of 15 seconds, then the maximum time is going to be 15+3+15+10+15 = 58 seconds

**How much can the user control this?**

It's possible depending on how webhook services are implemented that a dropped connection still makes changes on the remote server and so a retry makes more changes than intended.. so I'm thinking at the very least the user needs to be able to opt out (advanced option on the action).. tho I also like the simplicity of just hiding this from the user.

I don't think they get a say in delays (maybe those are mailroom config options). Also not sure about trusting `Retry-After` headers as those could be long delays.

**Comment by ericnewcomer** [comment]
I wonder if maybe retries should be opt-in. The reason being that us assuming idempotentcy doesn't feel right for a POST. To that end, it feels the default for a GET should be consistent.

I don't think we need to surface the backoff strategy and what you suggest there makes sense to me.

**Comment by nicpottier** [comment]
Ya, I think a header should be used if peeps want a retry for a POST. They can always wrap those if they so wish if someone downstream doesn't set it by default.

**Comment by rowanseymour** [comment]
The worst case scenario here is flows with multiple webhook calls that always timeout start taking minutes to complete per user. Maybe if we start having problems there we could also consider that URLs get temporarily blacklisted if they consistently timeout.

**Comment by nicpottier** [comment]
If services can't be up after three tries and 10 seconds then any kind of additional retry logic just seems silly.

**Comment by nicpottier** [comment]
(and our org fair queuing should mean that the effects of someone calling slow / dead services are only felt on their org, not others)

**Comment by rowanseymour** [comment]
@nicpottier what's the argument for a header vs an option in the UI that defaults to disabled?

**Comment by nicpottier** [comment]
Whether a POST has actually accomplished its work is kind of a game-time decision. IE, you may get an error after committing but before writing the request, in which case you wouldn't want to ask for a retry. I think that's why it is generally done as a header switch as opposed to a static element. Also fewer UI elements the better, in the vast majority of cases retrying a POST is dangerous and it should be the server opting into that.

**Comment by nicpottier** [comment]
Sounds like maybe having the server set `Retry-After` would be a sane way of doing this?

**Comment by nicpottier** [comment]
Looking at: https://tools.ietf.org/html/rfc2616#section-10.5.4

It kinda seems like the safest strategy for general retries should be:
 * only retry on 429, 503 and connection errors
 * only retry POST/PUT/DELETEs if `Retry-After` is set (we could ignore the value there and do our own backoff)

**Comment by chris-erickson** [comment]
I would be OK with most all of this to be opt-in, though as I mentioned in the group that [AWS has retry baked into their libraries](https://aws.amazon.com/premiumsupport/knowledge-center/lambda-function-retry-timeout-sdk/) so it's probably often what a user actually wants/would like.  

Additionally they have done some work on retries, [specifically around jitter and exponential backoff](https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/) (I could actually see this being useful for us, as sometimes our failures could be during a large push that might have a lot of requests hitting very close to the same instant).  A fixed retry schedule could be counterproductive in high-traffic cases (see linked article) but I'd take anything over nothing right now.

I think it's fair to say that people using RP may be quite unfamiliar with these concepts and making it _on by default_ could have some shockingly weird effects if you don't know about it.  I would be fine turning it on according to my expectations of that destination webhook.

Internally we use the [backoff tool a lot](https://github.com/litl/backoff), and it presents some options that are quite useful and easy to understand.  Not saying the full set should be implemented, but it's a good reference point.

Summary of my ideas:
- **When to retry**, yes, HTTP failure codes
- **How many times**, we typically try ~3 times before bailing out, sometimes asking the user in between if they'd like us to (messaging is something like "we're super busy do you want us to try again?")
- **How much control** - On/off is great, I'd love some control _sometimes_, but it's not required to make this useful.  Doing it header vs a UI switch isn't that important, but seems odd to send some custom header down the pipe when it's only used internally.

Another thought - some of our web hooks are really weird in how they use HTTP verbs because we can't formulate a GET body.  I know it's not entirely conventional to do this [though there are examples](https://stripe.com/docs/api/subscriptions/list?lang=curl) (Stripe uses a GET with form encoding to provide a lookup token).  So, we use a POST for an endpoint that is idempotent.  I can't remember exactly the reasons but I know we have had a very challenging time getting some content into the QS parameter when we are doing a GET that isn't changing data (ie. an address lookup).  Using a POST body made this more reliable since there's less double-escaping taking place.  Also, some APM libraries are more OK logging query-strings, whereas a body is rarely logged, so it helps to keep PII-adjacent data out of query strings too.  Sorry this thought went so long, but it's to say that being able to edit the GET body would help the idempotency case for us.

**Comment by nicpottier** [comment]
Note AWS says retry only 503s unless you know what you are doing is idempotent:
  https://docs.aws.amazon.com/apigateway/api-reference/handling-errors/

**Comment by rowanseymour** [comment]
The way go handles this is a header on the request, see https://github.com/golang/go/issues/19943#issuecomment-421092421. The problem with relying on a header on the response is there's no way to set it for connection errors etc, and no way to set it if you don't control the service to start off with.

I would definitely prefer a UI element to a request header because the former is discoverable.

I think it's ok that _if users are opting into this_, they understand that the other side needs to be implemented in an atomic way, or they need to make requests idempotent. On their own heads be it.

Also think it only makes sense to use `Retry-After` if it's less than the backoff we would use.

**Comment by chris-erickson** [comment]
I'm sure everyone wants to hear this, but how will we know an endpoint is potentially performing really poorly?  If something is constantly retrying, but eventually succeeding we may never know.  At least now we see the errors.  Personally I'd love some async way to log or report this so it stays out of the way in RP.  Tracking errors in mailroom log statements (not user logs) would let us ship logs off to Elastic and do our own out of band analysis and not put further load on the DB.

**Comment by nicpottier** [comment]
Connection errors should always be retried, that's a different case. We are talking about what you do when you actually get a status code back no?

I don't see any downside to retrying everything without having to worry users about it, and then just use the same rules as Amazon has for the rest. I really don't want our UI to start having more and more options for everything, especially when the default cause is we want it checked anyways. We are talking .001% of users ever wanting to control POST retries.

@chris-erickson please stay on thread or start another issue if you want for logging

**Comment by nicpottier** [comment]
I guess we could let "client" control it by having the flow author set "Idempotency-Key" on POSTs actually. They can already set that header as is and then they can control how to slice what is unique about that request.

**Comment by rowanseymour** [comment]
As I wrote in my first comment, AFAIK it's not always safe to retry in the case of a connection error. That connection may have dropped half way thru doing something.

**Comment by nicpottier** [comment]
Well as a first shot why don't we turn it on for everything that is GET and everything else when there is "Idempotency-Key" set?

**Comment by rowanseymour** [comment]
Fine with switching it on for all `GET`s and seeing how things go. 

My issue with relying on a request header for other verbs is that it seems unlikely any user would ever discover that so only the people in this thread will ever get to use it. Should/could there be something in the UI that explains the rules about retrying? If so wouldn't it be better to just have checkbox with an explanation?

**Comment by nicpottier** [comment]
I don't think adding a UI element for a .01% case is the right call, no.

Using that header is an emerging standard, so perhaps that will get more common, otherwise documentation / tickets should address the rest. Considering how often we get tickets about people wanting to retry POSTs (IE, never) then I think that should be fine.

We don't want to make the UI more complicated for things that don't affect 99.9% of users.

**Comment by chris-erickson** [comment]
I had no idea headers could contain expressions till now 🤦🏻‍♂️, but I guess we'd have to farm out generating something more complex than a value we already know (like user uuid) w/o a SHA or something of the body.  I'd be happy with all GET and a special header for now.  Worst case I fear is something that is a GET, and really shouldn't be retried on a failure because of legacy usage somehow.  Seems like a case for being able to enable/disable per webhook, but probably would be manageable to audit all GET web hooks one time before deploying this to make sure nothing old needs to be altered.

**Comment by rowanseymour** [comment]
My thinking on that is that either something is worth having as an advanced 1% feature or it isn't, and if it is, it should implemented in a way that discoverable to advanced users. No secret features.

But if doing all `GETs` and requests with `Idempotency-Key` works for everyone then that seems like a good place to start 👍

**Comment by rudigiesler** [comment]
I quite like the `Idempotency-Key` idea. That could easily be set to something like `@run.uuid`, and a lot simpler solution that implementing retry loops in flows.

In terms of what gets retried, I feel like limiting to 429, 503 errors might be a bit too limiting, a lot of services are behind a reverse proxy which will return a 502 on temporary outages, or 504 if upstream is under high load and taking too long to respond, both of which seem like cases where we want to retry.

Also, restricting POST request retries to only responses with `Retry-After` headers seems a bit restricting if we don't control the upstream API. There are some APIs that are idempotent (the key is in the body), so are safe to retry, but don't set a `Retry-After` on temporary failures.

For documenting, the place I came across when I looked for info when creating webhooks was https://help.nyaruka.com/en/articles/1911235-calling-a-webhook-new-editor , so mentioning the `Idempotency-Key` functionality there would probably be a good place.

**Comment by rowanseymour** [comment]
This https://github.com/hashicorp/go-retryablehttp library does retries on all 5XX responses except 501. I was thinking maybe anything over 501 is better since we usually see 500s when server code is blowing up. Obviously these sorts of things are easy to tweak once I get the basics working.

**Comment by rudigiesler** [comment]
Looks good. I see it does either exponential backoff, or linear backoff with jitter, but not both (exponential backoff with jitter), but I would consider that a nice-to-have.

I found this article very useful when implementing retries, if something more fancy is required: https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/

**Comment by rowanseymour** [comment]
@rudigiesler take a look at https://github.com/nyaruka/goflow/pull/820. It's not explicitly doing exponential or jitter but.. at the mailroom level you would configure whatever timeouts you want

**Comment by rowanseymour** [comment]
Merged and released in mailroom v5.3.15
