### ISSUE TITLE
Group modifier should disallow adding to dynamic groups

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/goflow#865]

**Comment by rowanseymour** [comment]
So as we've used modifiers to date, they have no concept of errors because we assume that the action validated all the inputs and turned errors into error events.

We have a few options here.. suppose the engine gets a `groups` modifier which has 2 groups and one of them is dynamic, it could..

1. Return an actual `error` making no changes to the contact
2. Ignore the dynamic group, log `contact_groups_changed event` for the other group
3. Log error event for the dynamic group, log `contact_groups_changed event` for the other group

Note that in the case of a dynamic group with a query error, modifiers can log error events

**Comment by nicpottier** [comment]
3) feels the most right to me.

**Comment by rowanseymour** [comment]
Yeah I think so too after I noticed they already do log error events in some cases
