### ISSUE TITLE
Invalid email addresses not caught by regex

### ISSUE THREAD

**Issue by tybritten** [nyaruka/goflow#901]
Email addresses that the user ends in a period are not valid but goflow allows it 
https://github.com/nyaruka/goflow/blob/ca4c21848a1a427defe40fa0858e2b6dc248c3e1/flows/routers/cases/tests.go#L498

so `user.@domain.com` is not valid but passes that regex.

**Comment by rowanseymour** [comment]
This is kinda "intentional"... we've always avoided trying to be too clever about validating email addresses by regexes.. because there's likely working addresses out there that don't play by the rules. I think this article sums up the reality fairly well https://medium.com/hackernoon/the-100-correct-way-to-validate-email-addresses-7c4818f24643

Unless this is causing problems.. I think I would still lean toward not trying to be too clever here.

**Comment by tybritten** [comment]
Thanks, I agree, just wanted to bring it to your attention.
